name: MineQuestParser
main: com.theminequest.MineQuest.MineQuestParser
version: 0.0.1-SNAPSHOT

author: JMonk

description: This plugin opens a port for communication with the MineQuest Quest Writer
website: www.theminequest.com

load: POSTWORLD
